# Generated by Django 5.0 on 2024-01-02 17:11

import common.utils.file_upload_paths
import common.validators.image_pdf_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattachment',
            name='attachment',
            field=models.FileField(upload_to=common.utils.file_upload_paths.quote_files_path, validators=[common.validators.image_pdf_extension_validator.image_pdf_extension_validator], verbose_name='Attachment'),
        ),
    ]
