# Generated by Django 5.0 on 2024-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_quoteattachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='due_date',
            field=models.DateTimeField(default='2024-01-11 12:45:00+00:00'),
            preserve_default=False,
        ),
    ]
