# Generated by Django 5.0 on 2024-01-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quoterequest_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests_as_supplier', to=settings.AUTH_USER_MODEL, verbose_name='Target Supplier'),
        ),
    ]
