# Generated by Django 5.0 on 2024-04-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quoterequest_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('bag', 'Bag / Bags'), ('barrel', 'Barrel / Barrels'), ('bushel', 'Bushel / Bushels'), ('cubic', 'Cubic Meter / Cubic Meters'), ('dozen', 'Dozen / Dozens'), ('gallon', 'Gallon / Gallons'), ('gram', 'Gram / Grams'), ('kilogram', 'Kilogram / Kilograms'), ('kilometer', 'Kilometer / Kilometers'), ('long', 'Long Ton / Long Tons'), ('meter', 'Meter / Meters'), ('metric', 'Metric Ton / Metric Tons'), ('ounce', 'Ounce / Ounces'), ('pair', 'Pair / Pairs'), ('pack', 'Pack / Packs'), ('piece', 'Piece / Pieces'), ('pound', 'Pound / Pounds'), ('set', 'Set / Sets'), ('short', 'Short Ton / Short Tons'), ('square', 'Square Meter / Square Meters'), ('ton', 'Ton / Tons')], max_length=50, verbose_name='Unit')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Per Product)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='TAX')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='product',
            field=models.ManyToManyField(to='quote.quoteproduct'),
        ),
    ]
