# Generated by Django 5.0 on 2024-01-02 17:11

import common.utils.file_upload_paths
import common.validators.image_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.buyers_profile_pictures_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.suppliers_profile_pictures_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Profile Picture'),
        ),
    ]
