version: "3.10"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  backend:
    command: python3 manage.py runserver 0.0.0.0:8000
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - uploads:/uploads
      - .:/app
volumes:
  uploads:
