# Generated by Django 5.0 on 2023-12-29 10:07

import common.utils.file_upload_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=common.utils.file_upload_paths.product_images_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'tiff', 'svg'])], verbose_name='Thumbnail'),
        ),
    ]
