# Generated by Django 5.0 on 2023-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, verbose_name='Is Returnable ?'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_deadline',
            field=models.IntegerField(default=30, verbose_name='Maximum Days To Return'),
        ),
    ]
