# Generated by Django 5.0 on 2024-01-07 12:07

import common.utils.file_upload_paths
import common.validators.image_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Thumbnail'),
        ),
    ]
