# Generated by Django 5.0 on 2024-01-18 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_privatecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecategory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
        migrations.AlterField(
            model_name='privatecategory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Private Category Supplier'),
        ),
    ]
