# Generated by Django 5.0 on 2024-01-12 07:21

import common.utils.file_upload_paths
import common.validators.image_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.ads_thumbnail_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Thumbnail')),
            ],
        ),
    ]
