# Generated by Django 5.0.6 on 2024-05-26 12:03

import common.utils.file_upload_paths
import common.validators.image_extension_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.ads_thumbnail_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Thumbnail')),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
