# Generated by Django 5.0.6 on 2024-05-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('payment_method', models.CharField(choices=[('DIR', 'Direct'), ('DIV', 'Divided')], max_length=3, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('O', 'Open'), ('CL', 'Closed'), ('CA', 'Canceled'), ('P', 'Pending Payment'), ('F', 'Finished')], default='O', max_length=2, verbose_name='Status')),
                ('delivery_date', models.DateTimeField()),
                ('payment_days', models.CharField(max_length=255)),
                ('opportunity_value', models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('B', 'Big'), ('E', 'Extraordinary')], max_length=3, verbose_name='Opportunity Value')),
                ('views', models.BigIntegerField(default=0, verbose_name='Views')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
    ]
