# Generated by Django 5.0 on 2024-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('P', 'Purchase'), ('R', 'Return'), ('W', 'Withdrawal')], max_length=20),
        ),
    ]
