# Generated by Django 5.0 on 2024-03-27 11:17

import common.utils.file_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.withdraw_approve_receipt_path),
        ),
    ]
