# Generated by Django 5.0.6 on 2024-05-26 12:03

import common.utils.file_upload_paths
import common.validators.image_extension_validator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name="Company's Email address")),
                ('phone', models.CharField(max_length=20, verbose_name="Company's Phone Number")),
                ('website', models.URLField(blank=True, null=True, verbose_name="Company's Website")),
                ('bio', models.TextField(blank=True, null=True, verbose_name="Company's Bio")),
                ('register', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Register')),
                ('company_profile_picture', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.company_profile_picture_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Profile Picture')),
                ('company_cover_picture', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.company_cover_picture_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Cover Picture')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Company Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edited On')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Company's Owner")),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
