# Generated by Django 5.0 on 2024-01-22 12:23

import common.utils.file_upload_paths
import common.validators.image_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.company_cover_picture_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Cover Picture'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.company_profile_picture_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Profile Picture'),
        ),
    ]
