# Generated by Django 5.0 on 2024-01-30 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_company_cover_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name="Company's Bio"),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 15, 43, 50, 776555, tzinfo=datetime.timezone.utc), verbose_name='Added On'),
        ),
    ]
