# Generated by Django 5.0 on 2024-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='supplier',
            new_name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='register',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Register'),
        ),
    ]
