# Generated by Django 5.0 on 2024-01-01 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_is_returnable_product_return_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('shipping_status', models.CharField(choices=[('OR', 'Ordered'), ('P', 'Shipping is being prepared'), ('OTW', 'On the way'), ('DE', 'Delivered')], default='OR', max_length=15, verbose_name='Shipping Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ordered Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash')], max_length=55, verbose_name='Payment Method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('products', models.ManyToManyField(blank=True, to='order.orderitem', verbose_name='Products')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='Tracking Number')),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('APR', 'Approved by Supplier'), ('OTW', 'On the way'), ('CMP', 'Return Completed')], default='AP', max_length=15, verbose_name='Return Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
