# Generated by Django 5.0 on 2024-01-02 16:05

import common.utils.file_upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('POO', 'Poor quality'), ('WRO', 'Wrong materials'), ('ADD', 'Shipped to a wrong address')], default='POO', max_length=15, verbose_name='Return Reason'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.return_request_files_path)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.returnrequest')),
            ],
        ),
    ]
