# Generated by Django 5.0 on 2024-01-04 19:07

import common.utils.file_upload_paths
import common.validators.image_video_extension_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_returnrequest_decline_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.return_request_files_path, validators=[common.validators.image_video_extension_validator.image_video_extension_validator])),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.returnrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnRequestImage',
        ),
    ]
