# Generated by Django 5.0 on 2024-01-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_returnrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('NOT', 'Not Requested'), ('AP', 'Applied'), ('DEC', 'Declined by Supplier'), ('APR', 'Approved by Supplier'), ('OTW', 'On the way'), ('CMP', 'Return Completed')], default='NOT', max_length=15, verbose_name='Return Status'),
        ),
    ]
